# Pipeline /.devops/pipeline-build-gulpw74framework-ci.yml

trigger:
  batch: true
  branches:
    include:
      - master
      - dev
      - feature/*
      - hotfix/*
      - release/*
pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

name: CI-$(date:yyyyMMdd)$(rev:.r)
jobs:
  - job: Main
    displayName: Main job
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
          checkLatest: true
      - task: CmdLine@2
        displayName: Install dependencies
        inputs:
          script: npm install
