# Pipeline /.devops/pipeline-build-gulpw74framework-ci.yml

trigger:
  batch: true
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

name: CI-$(date:yyyyMMdd)$(rev:.r)
jobs:
  - job: Main
    displayName: Main job
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
          checkLatest: true
      - task: Npm@1
        displayName: Install dependencies
        inputs:
          command: 'install'
          customEndpoint: 'registry.npmjs.org'
      - task: Npm@1
        displayName: Publish package to npm registry
        inputs:
          command: 'publish --access public'
          publishEndpoint: 'registry.npmjs.org'
